# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "rerun", "~> 0.14.0"

gem "websocket-eventmachine-server", "~> 1.0"

gem 'eventmachine', '1.2.7', git: 'https://github.com/eventmachine/eventmachine.git', tag: 'v1.2.7'

