name: "Hacer pruebas y lanzar apk"
run-name: Despliegue de @${{ github.actor }}
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "jiron_anime"

    name: Proceso de buildeoo

    steps:
      - uses: actions/checkout@v1

      - uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          envkey_GOOGLE_SERVER_CLIENT_ID: ${{ secrets.GOOGLE_SERVER_CLIENT_ID }}
          envkey_SERVER_URL: ${{ secrets.SERVER_URL }}
          envkey_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          envkey_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          directory: "jiron_anime"
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.24.1"

      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk --debug --split-per-abi

      - name: Set Tag Name
        id: set_tag
        run: echo "tag=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "jiron_anime/build/app/outputs/apk/debug/*.apk"
          tag: ${{ env.tag }}
          # token: ${{ secrets.TOKEN }}
